### PR TITLE
Configure express middlewares.

### PR DESCRIPTION
**Pull request by uxFeranmi**
The main routes are...

POST `/api/trim` Generate a new trimmed URL
GET `/` Render landing page
GET `/:urlCode` Redirect to the long_url

### CODE REVIEW

**Review by shonubijerry — COMMENTED** [review]
This PR will not be closed, it is a proof of work from @Stacalpha @Ennyola @Endowmissy it wasn't merged directly to the codebase, but parts of it was used to improve the product.

**Review by Emex4gman — COMMENTED** [review]
bro so many changes, hw do we keep track.

**Comment by Emex4gman** [comment]
so it won't be merged also??

**Comment by shonubijerry** [comment]
No it won't

**Comment by uxFeranmi** [comment]
So I did a thing. I replaced the entire project folder with the files from upstream/develop. This means that as of right now, this branch should be identical with hngi:Develop. The pull request can thus be merged without any changes being made to the codebase. So @Endowmissy and @Ennyola can be featured in the commit history. 

Please see if this is ok @shonubijerry .

**Pull request closed without merging**
