### PR TITLE
form-validator.js

### PR DESCRIPTION
**Pull request by Prinok77**
This file is created and pushed in response to the task assigned to me on Hng6i-Stage 5  on 8/10/19 by 4.53pm WAT on the  NodeJs  Track of  HNG 6 Internship Slack Channel. The task is to create an input validator for forms on the Url Shortener App modelled on clip.ng. This file is the response to that task.

### CODE REVIEW

**Review by seyiogunjuyigbe — CHANGES_REQUESTED** [review]
Oh... bro, you missed the task... We are neither using authentication nor registration. You're creating form validation on the front end to check the inputted urls if correct and also if the clipped url doesn't already exist in the user's DB

**Review by shonubijerry — CHANGES_REQUESTED** [review]
Your efforts are appreciated. But you need to work with the team files. Your task actually requires that you create middlewares that validates requests.

**Comment by Prinok77** [comment]
The requested changes have been made. Thank you.

**Review by shonubijerry — CHANGES_REQUESTED** [review]
Delete the form-validator.js file as we don't need it. Can you make the input-validator.js file align with the codebase. It should be the first middlewares when user make request to the POST endpoint. For example
`app.post('/api/trim', validateInput, bla bla, bla)`

**Pull request closed without merging**
